name: Deploy Kanji Flash Card App

on:
    push:
        branches:
            - master
        paths:
            - client/**

    workflow_dispatch:


permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:

    deploy:

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci
              working-directory: ./jpflash/client

            - name: Build
              run: npm run build
              working-directory: ./jpflash/client

            - name: Configure Pages
              uses: actions/configure-pages@v5
              working-directory: ./jpflash/client

            - name: Upload Pages Artifact
              working-directory: ./jpflash/client
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './dist'

            - name: Deploy To GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              working-directory: ./jpflash/client
